### ISSUE TITLE
Analysis view

### ISSUE THREAD

**Issue by Akira83** [amgrubb/BloomingLeaf#78] opened 2017-09-22 14:54 UTC
The output from "Explore Possible Next States" is not working properly.

**Comment by Akira83** [comment] 2017-09-22 16:05
I'm getting an error when executing "Explore possible next states". 
I not able to create an output to test the analysis view.

Test case:
Step1 - Two independent node without initial values.
[bug_step1.txt](https://github.com/amgrubb/BloomingLeaf/files/1325105/bug_step1.txt)
[bug_step1_result.txt](https://github.com/amgrubb/BloomingLeaf/files/1325104/bug_step1_result.txt)
Working.

Step2 - select 3|7 step and generate the following input for the solver:
[bug_step2.txt](https://github.com/amgrubb/BloomingLeaf/files/1325103/bug_step2.txt)
Generates an exception.

**Comment by g2hchang** [comment] 2017-09-22 17:35
Hi Akira,
I am not sure if I can help, but do you mind providing brief screen capture of how to reproduce the bug?
I want to test it out myself to reproduce and see if I can find the bug.
Thanks,

**Comment by Akira83** [comment] 2017-09-22 18:04
Hello @g2hchang,
to execute the bug it's just necessary to run the bug_step2.txt in the SolveModel.java
Actually the other 2 files are not necessary, just wanna put there to certify that the output is correct.
I have debug it but it seems to be in the Solver and I didn't want to mess with Alicia code.

**Comment by amgrubb** [comment] 2017-09-22 23:40
This bug might only exist because my pull request wasn't merged yet. ;)

**Comment by amgrubb** [comment] 2017-09-25 19:19
```{
  "analysis": {
    "action": "allNextStates",
    "maxAbsTime": "100",
    "conflictLevel": "S",
    "numRelTime": "3",
    "absTimePts": null,
    "currentState": "2|83",
    "initialAssignedEpoch": [
      "TE1_83",
      "TA0_0",
      "E0001_83",
      "TR3_61",
      "TR2_92",
      "TR4_85"
    ],
    "initialValueTimePoints": [
      "0",
      "61",
      "83",
      "85",
      "92"
    ],
    "elementList": [
      {
        "id": "0001",
        "status": [
          "0011",
          "0011",
          "1100"
        ]
      },
      {
        "id": "0001",
        "status": [
          "0011",
          "0011",
          "1100"
        ]
      }
    ]
  },
  "model": {
    "actors": [
      
    ],
    "intentions": [
      {
        "nodeActorID": "-",
        "nodeID": "0000",
        "nodeType": "G",
        "nodeName": "Goal_0"
      },
      {
        "nodeActorID": "-",
        "nodeID": "0001",
        "nodeType": "G",
        "nodeName": "Goal_1"
      }
    ],
    "links": [
      
    ],
    "dynamics": [
      {
        "intentionID": "0000",
        "dynamicType": "R",
        "markedValue": "0000",
        "line": null
      },
      {
        "intentionID": "0001",
        "dynamicType": "SD",
        "markedValue": "1100",
        "line": null
      }
    ],
    "constraints": [
      
    ]
  }
}

I think I have identified this as the error.
![screen shot 2017-09-25 at 3 17 22 pm](https://user-images.githubusercontent.com/6596937/30826505-d7736556-a204-11e7-84ad-3afc75d491b3.png)

I will try to fix it now. :)

**Closed** 2017-09-28 19:35 UTC
Labels: bug, help wanted
